set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(AARCH64_GCC_INSTALL_ROOT "/opt/aarch64" CACHE PATH "AArch64 toolchain root")

set(CMAKE_C_COMPILER "${AARCH64_GCC_INSTALL_ROOT}/bin/aarch64-none-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "${AARCH64_GCC_INSTALL_ROOT}/bin/aarch64-none-linux-gnu-g++")

set(CMAKE_FIND_ROOT_PATH "${AARCH64_GCC_INSTALL_ROOT}/sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# OpenCV specific
set(WITH_HIGHWAY ON CACHE BOOL "Use Highway")
set(CPU_BASELINE "NEON" CACHE STRING "")
set(CPU_DISPATCH "" CACHE STRING "")
